config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:create, :update, :destroy] do
    	member do 
    		patch '/task_up', to: 'tasks#task_up'
  			patch '/task_down', to: 'tasks#task_down'
  		end
  	end
  end

  resource :persons, only: [:show, :update]

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  validates :body, presence: true
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	belongs_to :user
	validates :title, presence: true
	
	default_scope { order('created_at') }
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :comments

	belongs_to :project
	belongs_to :user

  validates :title, presence: true

	default_scope { order('prioritise') }

	def task_prioritise (id, flag)
		flag==1 ? up = -1 : up = 1
		flag==-1 ? down = -1 : down = 1
		task2 = Task.find_by project_id: id, prioritise: (self.prioritise + flag)
		if task2
			task2.prioritise += up
			task2.save
			self.prioritise += down
			self.save
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :tasks
  has_many :comments
  has_many :authorizations

  mount_uploader :avatar, AvatarUploader
  
  devise :database_authenticatable, :registerable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_oauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization

    email = auth.info[:email]
    user = User.where(email: email).first
    if user
      user.create_authorization(auth)
      user.avatar = auth.info[:image]
    else
      password = Devise.friendly_token[0, 20]
      user = User.create!(email: email, avatar: auth.info[:image], password: password, password_confirmation: password)
      user.create_authorization(auth)
    end
    user
  end


  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    end
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def show
  	@user = current_user
  end

  def update
  	@user = current_user
    @user.avatar = user_avatar_params[:avatar]
    @user.save!    
    redirect_to persons_path
  end

  def user_avatar_params
  	 params.require(:user).permit(:avatar)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)
    @project.save
    flash.now[:notice] = 'Project was successfully create.'
  end

  def update
    if @project.update(project_params)
     flash.now[:notice] = 'Project was successfully updated.'
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

 
  def destroy
    @project.destroy
    flash.now[:notice] = 'Project was successfully destroyed.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :task_up, :task_down]
  before_action :find_project, only: [:create, :destroy, :task_up, :task_down]
  before_action :authenticate_user!

  respond_to :js

  def create
    @task = current_user.tasks.create(task_params.merge(project_id: @project.id, prioritise: @project.tasks.count + 1))

    flash.now[:notice] = 'Your task successfully created.'
    respond_with(@task)
  end

  def update
    if @task.update(task_params)
      flash.now[:notice] = 'Task was successfully updated.'
      render nothing: true, status: 200
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    flash.now[:notice] = 'Your task successfully delete.'
    respond_with(@task)
  end

  def task_up
    @task.task_prioritise(@project.id, -1)
  end

  def task_down
    @task.task_prioritise(@project.id, 1)
  end

  private

    def find_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :done)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	redirect_to projects_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def class_title(bool)
		bool ? 'task_title_complete' : 'task_title'
	end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.slim
- if notice.present?
  p.alert.alert-success= notice
- if alert.present?
  p.alert.alert-danger= alert

app/views/layouts/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new Project</h4>
      </div>
      <div class="modal-body">
        <%= text_field_tag :title, "", id: "new_project_title", class: "form-control" %>    
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag 'Save', id: "new_project_submit", class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="bg"> 
    <%= image_tag ("bg.png") %>
  </div>
	<div class="container" id="content">
		<div class="row">
      <div class="col-md-8 col-md-offset-2" >
        <div class="logout">
          <% if user_signed_in? %>
            <span class="avatar">
              <%= link_to (image_tag (current_user.avatar_url(:thumb).to_s), title: 'Profile'), persons_path %>
            </span>
            <%= link_to (image_tag ("logout.png"), title: 'Logout'), destroy_user_session_path, :method => :delete%>
          <% end %>
        </div>
        <div class="page-header">
          <div class="flash">
            <%= render "layouts/flash"%>
          </div>
          <h1><%= link_to 'SIMPLE TODO LISTS', root_path %></h1>
          <h4>FROM RUBY GARAGE</h4>
        </div>
        <div class="yield">
				  <%= yield %>
        </div>
         
        <%= render "layouts/modal"%>   
      </div>
    </div>	
	</div>
    <footer>
      <p>&copy; Ruby Garage</p>
    </footer>
</body>
</html>

app/views/persons/profile.html.slim
= @user.email
br
- if @user.avatar_url
		div.profile_avatar
			= image_tag (@user.avatar_url(:thumb).to_s)
br
= form_for @user, url: persons_update_path, :html => {:multipart => true}, method: :patch do |f|
  p
    = f.file_field :avatar 
  p
  	= f.submit 

app/views/persons/show.html.slim
= @user.email
br
- if @user.avatar_url
		div.profile_avatar
			= image_tag (@user.avatar_url(:thumb).to_s)
br
= form_for @user, url: persons_path, :html => {:multipart => true}, method: :patch do |f|
  p
    = f.file_field :avatar 
  p
  	= f.submit 

app/views/projects/_project.html.slim
div id="tasks_errors_#{project.id}"
div.project id= "project_#{project.id}"
  .ProjectTitle
    = image_tag("project.fw.png")
    span.title id="project_title_#{project.id}"
      = project.title
    span.edit id="edit_#{project.id}"
      span
        = text_field_tag :title, project.title, id: "new_project_title_#{project.id}"
      .btn.btn-primary id="ok_edit_#{project.id}"
        i.fa.fa-check
      .btn.btn-primary id="cancel_edit_#{project.id}"
        i.fa.fa-times
    div.right_side
      div.pencil
        = image_tag ("pencil.fw.png"), id: "edit_project_#{project.id}", class: "edit_project", data: { project_id: project.id}
      div.trash id="trash_#{project.id}"
        = link_to (image_tag ("trash.fw.png")), project, data: {:confirm => 'Are you sure?'}, :method => :delete, remote: true, id: "trash_#{project.id}"
  div.addtask
    .row
      div.col-lg-12.col-md-12.col-sm-12.col-xs-12
        div.col-md-1.col-sm-1.col-xs-1.plus
          =image_tag ("plus.fw.png")
        div.form.col-md-11.col-sm-11.col-xs-11.input-group
          = form_for [project, Task.new], remote: true,  data: { project_id: project.id }, html: { class: "input-group"} do |f|
            .field
              = f.text_field :title, placeholder: "Start typing here to create a task..", id: "title_#{project.id}", class: "form-control"
            .span.input-group-btn 
              = f.submit 'Add Task', class: "btn btn-default"
  .tasks id="tasks_#{project.id}"
    = render 'tasks/list', project: project

app/views/projects/create.js.erb
$('#myModal').modal('hide');
<% if @project.errors.present? %>
	<% @project.errors.full_messages.each do |message| %>
		showFlashMesage('<p class="alert alert-danger"><%= j message %></p>');
	<% end %>
<% else %>
	<% if @project.persisted? %>
		$(".projects").append('<%= j render "projects/project", project: @project %>');
		showFlashMesage('<%= j render "layouts/flash" %>');
	<% end %>
	<% end %>
	

app/views/projects/destroy.js.erb
$('div#project_' + "<%=@project.id%>").remove();
showFlashMesage('<%= j render "layouts/flash" %>');
	

app/views/projects/index.html.slim
div.projects
  - @projects.each do |project|
    = render 'project', project: project       
div.center
  = button_tag class: "ngdialog-button ngdialog-button-secondary", data: { toggle: 'modal', target: '#myModal' } do
    = image_tag ("plus_for_btn.fw.png")
    | Add TODO List


/ ul
/   - @projects.each do |project|
/     div id="tasks_errors_#{project.id}"
/     li
/       = project.title
/       span
/         = link_to ' Show ', project
/       span
/         = link_to ' Edit ', edit_project_path(project)
/       span
/         = link_to ' Destroy ', project, data: {:confirm => 'Are you sure?'}, :method => :delete
/       = form_for [project, @task], remote: true,  data: { project_id: project.id } do |f|
/         .field
/           = f.label :title
/           = f.text_field :title
/         .actions = f.submit
/       .tasks id="tasks_#{project.id}"
/         = render 'tasks/list', project: project

/ br

/ = link_to 'New Project', new_project_path

app/views/tasks/_list.html.slim
ul.todo-list
	- project.tasks.each do |task|
	  li.task id="task_#{task.id}"
	    div.row
	      div.col-md-1.ol-sm-1.col-xs-1
	        div.qwer
	        	= check_box_tag 'checked_in', task.id , task.done, :class => "task-check", data: { project_id: project.id }
	      div.col-md-9.col-sm-9.col-xs-9.task
	        span id="task_title_#{task.id}" class=(class_title(task.done))
	        	= task.title 
	        	= task.prioritise
	        span.edit id="edit_task_#{task.id}"
			      span
			        = text_field_tag :title, task.title, id: "new_task_title_#{task.id}"
			      .btn.btn-primary id="ok_edit_task_#{task.id}"
			        i.fa.fa-check
			      .btn.btn-primary id="cancel_edit_task_#{task.id}"
        			i.fa.fa-times
	      div.col-md-2.col-sm-2.col-xs-2.right_side
	      	div.pencil
		      	div.arrows
							= image_tag ("arrow-up.png"), class: "prioritise", data: { project_id: project.id, task_id: task.id, directive: "task_up" }
							= image_tag ("arrow-down.png"), class: "prioritise", data: { project_id: project.id, task_id: task.id, directive: "task_down" }
	        div.pencil
	        	= image_tag ("pencil_task.fw.png"), class: "edit_task", data: { project_id: project.id, task_id: task.id } 
	        div.trash
	         = link_to (image_tag ("trash_task.fw.png")), [project, task], :method => :delete, remote: true 

app/views/tasks/create.js.erb
<% if @task.errors.present? %>
	<% @task.errors.full_messages.each do |message| %>
		showFlashMesage('<p class="alert alert-danger"><%= j message %></p>')
	<% end %>
<% else %>
	$('#tasks_' + "<%=@project.id%>").html('<%= j render "tasks/list", project: @project %>');	
	$('#title_' + "<%=@project.id%>").val('');
	$('#tasks_errors_' + "<%=@project.id%>").html('');

	showFlashMesage('<%= j render "layouts/flash" %>');
	
	
<% end %>

app/views/tasks/destroy.js.erb
$('#tasks_' + "<%=@project.id%>").html('<%= j render "tasks/list", project: @project %>');
showFlashMesage('<%= j render "layouts/flash" %>');

app/views/tasks/task_down.js.erb
$("#tasks_<%= @project.id %>").html("<%= j render 'tasks/list', project: @project %>");

app/views/tasks/task_up.js.erb
$("#tasks_<%= @project.id %>").html("<%= j render 'tasks/list', project: @project %>");

app/views/welcome/index.html.slim
.col-md-6.center.buttons
	= link_to "SignIn", new_user_session_path, class: "btn btn-primary btn-lg"
.col-md-6.center.buttons
	= link_to "SignUp", new_user_registration_path, class: "btn btn-primary btn-lg"